# Generated by Django 5.2.8 on 2025-11-24 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transfert', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('banque_name', models.CharField(max_length=200)),
                ('numero_compte', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('expediteur_nom', models.CharField(max_length=200)),
                ('expediteur_pays', models.CharField(blank=True, max_length=100)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('echeance_date', models.DateTimeField(blank=True, null=True)),
                ('beneficiaire_nom', models.CharField(blank=True, default='', max_length=200)),
                ('beneficiaire_compte', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiaire_telephone', models.CharField(blank=True, default='', max_length=50)),
                ('beneficiaire_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.payment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
